# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/abenz1267/walker
%global goipath         github.com/abenz1267/walker
Version:                0.7.4

%gometa -L -f

%global common_description %{expand:
Application launcher similar to Rofi etc. . Wayland native.}

%global golicenses      LICENSE
%global godocs          README.md cmd/version.txt

Name:           golang-github-abenz1267-walker
Release:        %autorelease
Summary:        Application launcher similar to Rofi etc. . Wayland native

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc README.md cmd/version.txt
%{_bindir}/*
%endif

%gopkgfiles

%changelog
%autochangelog
